### ISSUE TITLE
Wrong indentation level for sleep function

### ISSUE THREAD

**Issue by Bjarten** [PacktPublishing/Practical-Python-Programming-for-IoT#1]
https://github.com/PacktPublishing/Practical-Python-Programming-for-IoT/blob/0717e92b6c645d4c97ef32d25ad7d46af1ab2c38/chapter02/dweet_led.py#L98

Hey, this line should be indented one more level, or it will never sleep for those two seconds.

**Comment by garyns** [comment]
Thanks for letting me know. I've fixed the indentation and pushed the change.
