### ISSUE TITLE
chapter02 button_pigpio.py and button_gpiozero.py use different debounce times

### ISSUE THREAD

**Issue by Soccertanker** [PacktPublishing/Practical-Python-Programming-for-IoT#2]
In chapter02, button_gpiozero.py uses debounce time of 0.1 seconds. button_pigpiozero.py uses debounce time of 10000 microseconds. I think the idea of chapter 2 is to execute the same functionality using pigpio and gpiozero, so this difference in debounce time can be confusing for readers.

10000 microseconds == 0.01 seconds != 0.1 seconds

**Comment by garyns** [comment]
Hi Eric,

Thank you for bringing this discrepancy to our attention.

I have confirmed that there is a type-o on Page 64 where I state that the debounce time is measured _milliseconds_ when it is actually meant to be _microseconds_.

I have added an Errata section at the following link discussing the misprint and implications.

[https://github.com/PacktPublishing/Practical-Python-Programming-for-IoT/tree/master/errata](https://github.com/PacktPublishing/Practical-Python-Programming-for-IoT/tree/master/errata)

I hope you are enjoying the book.

Thanks again,
Gary.
