### ISSUE TITLE
Chapter 05 install requirements is faling

### ISSUE THREAD

**Issue by StanSvec** [PacktPublishing/Practical-Python-Programming-for-IoT#3]
**Failing package**
RPi.GPIO
**Error**
`error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1`
**Solution**
Run before pip install: `export CFLAGS=-fcommon`
**Solution source**
[Ask Ubuntu](https://askubuntu.com/questions/1290037/error-while-installing-rpi-gpio-as-error-command-errored-out-with-exit-status)

**Comment by garyns** [comment]
Sorry, I do not have enough information to comment further, other than please ensure that you are meeting the technical requirements mentioned in the book, which include using Raspberry Pi OS (Debian).
