### ISSUE TITLE
Chapter 4 - mosquitto.conf needs to allow anonymous

### ISSUE THREAD

**Issue by paper-skyline** [PacktPublishing/Practical-Python-Programming-for-IoT#5]
With a default install of mosquitto, it throws the following error unless you modify either the mosquitto.conf file or mostquitto_pyiot.conf file to `allow_anonymous true`

`Connection error: Connection Refused: not authorised.`

**Comment by garyns** [comment]
Thanks. This must be a change since the original release of the config. I've noted the change for the 2nd edition of the book.
