### ISSUE TITLE
Chapter 3 not supporting Python 3.11.2 Flask

### ISSUE THREAD

**Issue by EZWoodworker** [PacktPublishing/Practical-Python-Programming-for-IoT#7]
Line 12 (from flask import Flask, request, render_template) gives the error: "ImportError: cannot import name 'Mapping' from 'collections'" in flask_api_server.py

**Comment by EZWoodworker** [comment]
I will no longer use the requirements.txt to set up the environment as it is outdated...

**Comment by garyns** [comment]
Hi, the code in this repo and its dependencies are frozen at the date of the book's publication so that the examples in the book match the code in this repo. Hence, you will need to use the library versions in requirements.txt to follow along with the book.
